### ISSUE TITLE
Cannot get examples to run

### ISSUE THREAD

**Issue by danbaragan** [revel/examples#33]
Following the documentation I was not able to run booking example.

* I have go.
* I have revel in $GOPATH/src/github.com/revel/revel  from go get github.com/revel/revel ; there are other dependencies installed in revel dir too.
* I have cloned this repo in another place and running `revel run booking` yields "import relative to unknown directory"
* I tried installing the examples like I did revel `go get github.com/revel/examples` yields "package github.com/revel/examples: no Go files in [...]"
* I tried moving the cloned "examples" dir to $GOPATH/src/github.com/revel and start it as in README with `go run github.com/reve/examples/booking` ; it yields "go run: no go files listed"
* I tried various other methods to get the example started that I don't think will help this issue further so I won't enumerate them.

Can you elaborate on how to run the examples ?
Thanks!

**Comment by danbaragan** [comment]
Ok, I lost it after moving the files under $GOPATH/src. I used `go run` instead of re`revel run`.
With `revel run` it works.
Isn't there a way to keep   example files/revel apps   in other than $GOPATH/src though?

**Comment by notzippy** [comment]
In Revel your project should be split up into MVC folders so just a single `go build` wont work .
Here are a couple of ways you can do this.

1) Extend the GOPATH to include your project `export GOPATH=%GOPATH%:/yourproject`. Have a script to automatically do this.
2) (my usual one) symlink the project path somewhere on an existing GOPATH folder.

If you have more questions we are on https://gitter.im/revel/community
