### ISSUE TITLE
email signup/ forgot password validation ?

### ISSUE THREAD

**Issue by jpca999** [revel/examples#37]
im very new to this golang, in the examples , do you have any code that provides email notifications that can  send  emails out for  signup/ forgot password validation ?

**Comment by notzippy** [comment]
That is a good idea, in the past I have used [go-mail](https://github.com/go-gomail/gomail) package to send emails from revel. I will try to add some examples using this

**Comment by jpca999** [comment]
@notzippy  Id really appreciate that.
