### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by talmai** [revel/examples#45]
Hi,

What's the license for this code?

**Comment by notzippy** [comment]
Same as revel/revel

**Comment by talmai** [comment]
Thanks for the feedback.

Would you mind actually adding a LICENSE file? I can even do the PR, if needed.

See https://choosealicense.com/no-permission/

**Comment by notzippy** [comment]
If you could do a PR that would be great @talmai

**Comment by notzippy** [comment]
On develop branch
